services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python -m manage runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
    depends_on:
      db:
        condition: service_healthy

  utility:
    build: .
    command: "bash"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://postgres@db/postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
